/*
 * File: app/view/FeedWindow.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.FeedWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.feedwindow',

    width: 500,
    iconCls: 'feed',
    title: 'Add Feed',
    plain: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    itemId: 'form',
                    bodyPadding: '12 10 10',
                    items: [
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            itemId: 'feed',
                            fieldLabel: 'Enter the URL of the feed to add',
                            labelAlign: 'top',
                            msgTarget: 'under',
                            autoSelect: false,
                            displayField: 'title',
                            queryMode: 'local',
                            store: 'DefaultFeedsStore',
                            valueField: 'url'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'container',
                    dock: 'bottom',
                    height: 24,
                    margin: 8,
                    layout: {
                        align: 'stretch',
                        pack: 'end',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'add',
                            width: 80,
                            text: 'Add Feed'
                        },
                        {
                            xtype: 'button',
                            itemId: 'cancel',
                            margin: '0 0 0 4',
                            width: 80,
                            text: 'Cancel'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});