/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({
    enabled: true,
    paths: {
        'Ext.ux': 'ux/'
    }
});


Ext.application({

    requires: [
        'Ext.Loader'
    ],
    models: [
        'Feed',
        'FeedItem'
    ],
    stores: [
        'FeedStore',
        'FeedItemStore',
        'DefaultFeedsStore'
    ],
    views: [
        'MyViewport',
        'FeedPanel',
        'FeedDetail',
        'FeedGrid',
        'FeedPost',
        'FeedInfo',
        'FeedWindow'
    ],
    controllers: [
        'FeedController'
    ],
    name: 'MyApp',

    launch: function() {
        Ext.syncRequire([
            'Ext.ux.PreviewPlugin'
        ]);
                Ext.create('MyApp.view.MyViewport');
    }

});
